# Generated by Django 5.1.3 on 2024-11-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artists', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('calification', models.FloatField()),
                ('cover', models.ImageField(upload_to='albums/covers/')),
                ('spotify_link', models.CharField(max_length=250)),
                ('awards', models.CharField(max_length=100)),
            ],
        ),
    ]
