# Generated by Django 5.1.3 on 2024-11-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='year',
        ),
        migrations.AddField(
            model_name='album',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
