# Generated by Django 5.1.3 on 2024-12-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_remove_album_year_album_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
